(function(){
'use strict';
let deferredPrompt=null;
const standalone=()=>matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;
const isiOS=/iphone|ipad|ipod/i.test(navigator.userAgent);
function css(){if(document.getElementById('fs-pwa-style'))return;const s=document.createElement('style');s.id='fs-pwa-style';s.textContent=`#fs-install-app{position:fixed;left:14px;bottom:16px;z-index:9998;min-height:42px;padding:0 14px;border:1px solid rgba(91,76,196,.22);border-radius:14px;background:rgba(255,255,255,.92);backdrop-filter:blur(14px);-webkit-backdrop-filter:blur(14px);box-shadow:0 8px 24px rgba(31,42,85,.16);color:#413a87;font:700 13px system-ui,-apple-system,"Segoe UI",sans-serif;cursor:pointer}#fs-install-app[hidden]{display:none!important}#fs-install-help{border:0;border-radius:20px;max-width:min(420px,calc(100vw - 32px));padding:0;box-shadow:0 24px 70px rgba(20,26,55,.28)}#fs-install-help::backdrop{background:rgba(15,23,42,.42);backdrop-filter:blur(3px)}#fs-install-help .box{padding:22px;color:#293247;font:15px/1.45 system-ui,-apple-system,"Segoe UI",sans-serif}#fs-install-help h3{margin:0 0 10px;font-size:21px}#fs-install-help p{margin:6px 0 16px;color:#687184}#fs-install-help button{width:100%;min-height:44px;border:0;border-radius:12px;background:#5b4cc4;color:white;font-weight:800}@media(max-width:520px){#fs-install-app{left:12px;bottom:12px;font-size:12px;min-height:40px;padding:0 12px}}`;document.head.appendChild(s);}
function help(){let d=document.getElementById('fs-install-help');if(!d){d=document.createElement('dialog');d.id='fs-install-help';d.innerHTML='<div class="box"><h3>Instalar Orçamentos CRM</h3><p id="fs-install-help-text"></p><button type="button">Entendi</button></div>';document.body.appendChild(d);d.querySelector('button').onclick=()=>d.close();}d.querySelector('#fs-install-help-text').textContent=isiOS?'No iPhone/iPad: toque em Compartilhar e depois em “Adicionar à Tela de Início”.':'No navegador, abra o menu e escolha “Instalar aplicativo” ou “Adicionar à tela inicial”.';d.showModal();}
function button(){if(standalone())return;css();let b=document.getElementById('fs-install-app');if(!b){b=document.createElement('button');b.id='fs-install-app';b.type='button';b.textContent='📲 Instalar app';document.body.appendChild(b);b.onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();const c=await deferredPrompt.userChoice;deferredPrompt=null;if(c.outcome==='accepted')b.hidden=true;}else help();};}}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;button();});
window.addEventListener('appinstalled',()=>{const b=document.getElementById('fs-install-app');if(b)b.hidden=true;deferredPrompt=null;});
function boot(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js',{scope:'./',updateViaCache:'none'}).then(r=>r.update()).catch(()=>{});button();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
